apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-bridge
  namespace: {namespace}
  labels:
    app: api-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-bridge
  template:
    metadata:
      labels:
        app: api-bridge
    spec:
      containers:
        -
          name: api-bridge
          image: "hello-chainlink/api-bridge"
          env:
            -
              name: FLASK_DEBUG
              value: "1"
            -
              name: RAPIDAPI_TOKEN
              value: "{api_token}"
          args: ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-bridge
  namespace: {namespace}
  labels:
    app: api-bridge
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: api-bridge
  type: LoadBalancer